/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import com.google.common.reflect.TypeToken;
import com.google.gson.Gson;
import com.google.gson.stream.JsonReader;
import org.junit.jupiter.api.Test;

import java.io.FileReader;
import java.lang.reflect.Type;
import java.util.List;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    private static final Type REVIEW_TYPE = new TypeToken<List<qout>>() {
    }.getType();
    @Test void appHasAGreeting() throws Exception {
        Gson gson = new Gson();
        JsonReader reader = new JsonReader(new FileReader("./app/src/main/resources/recentquotes.json"));
        List<qout> data = gson.fromJson(reader, REVIEW_TYPE);
        assertEquals(138,data.size());
    }
}
