/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import com.google.common.reflect.TypeToken;
import com.google.gson.Gson;
import com.google.gson.stream.JsonReader;

import javax.xml.transform.Result;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.lang.reflect.Type;
import java.util.List;

public class App {

    private static final Type REVIEW_TYPE = new TypeToken<List<qout>>() {
    }.getType();
    public static void main(String[] args) throws Exception {

        Gson gson = new Gson();
        JsonReader reader = new JsonReader(new FileReader("./app/src/main/resources/recentquotes.json"));
        List<qout> data = gson.fromJson(reader, REVIEW_TYPE);
        System.out.println(data.size());
        int range = (137 - 0) + 1;
        int x=(int)(Math.random() * range) + 0;
            System.out.println(data.get(x));
            System.out.println("-----------------------------------------------------------------------------");
        }

}
